name: Github Pages

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Publish to Pages
    steps:
      - uses: actions/checkout@v3 # Only works with v2
        with:
          token: ${{ secrets.PAT_TOKEN }}
#         name: Checkout
      - uses: subosito/flutter-action@v1
        name: Flutter Action
      - uses: bluefireteam/flutter-gh-pages@v7
        name: Flutter Web Build and Publish
